### PR TITLE
remove comma in default hash

### PR DESCRIPTION
**Pull request by suyograo**

### CODE REVIEW

**Comment by suyograo** [comment]
nobody saw this :) it was friday :)

**Comment by jordansissel** [comment]
brownie

The brownie in this picture is the comma you are trying to destroy. IT REFUSES.

**Comment by suyograo** [comment]
this deserves a @whack approved facepalm gif

suyog

**Comment by jordansissel** [comment]
I mean, to be fair, the PR subject says exactly what the change does. :P

**Comment by jordansissel** [comment]
Teamwork facepalmery.

facepalm

**Pull request closed without merging**
